/**
 * Disciplines & Powers compendium.
 *
 * One `discipline` container per Discipline plus its individual `power` items,
 * ordered by level. Fields are mechanical facts (level, Rouse cost, dice pool,
 * amalgam prerequisite); descriptions are original one-line functional
 * summaries — no rulebook prose.
 *
 * Verified against the Paradox VtM wiki discipline pages (all powers, all
 * sources): Corebook, Players Guide, Companion, Cults of the Blood Gods,
 * Sabbat, Chicago by Night, Gehenna War, Blood Sigils, Blood Stained Love,
 * Winter's Teeth, Live from the Succubus Club, Tattered Façade, Fall of London,
 * Second Inquisition, Anarch, Forbidden Religions, Book of Nod Apocrypha.
 */

import { D, Power } from "./_helpers.mjs";

const AM = (discipline, level) => ({ discipline, level });

/* --- Discipline containers ------------------------------------------------ */
const disciplines = [
  D({ key: "animalism", name: "Animalism", desc: "Command over beasts and the vampire's own inner Beast." }),
  D({ key: "auspex", name: "Auspex", desc: "Preternaturally heightened senses and psychic perception." }),
  D({ key: "bloodSorcery", name: "Blood Sorcery", desc: "The manipulation of blood as an occult tool; enables Rituals." }),
  D({ key: "celerity", name: "Celerity", desc: "Supernatural speed and reflexes." }),
  D({ key: "dominate", name: "Dominate", desc: "Bending mortal and vampire minds to the user's will." }),
  D({ key: "fortitude", name: "Fortitude", desc: "Inhuman toughness and resistance to harm." }),
  D({ key: "obfuscate", name: "Obfuscate", desc: "Concealment, disguise, and passing unseen." }),
  D({ key: "oblivion", name: "Oblivion", desc: "Command of shadow and the restless dead; enables Ceremonies." }),
  D({ key: "potence", name: "Potence", desc: "Raw supernatural strength." }),
  D({ key: "presence", name: "Presence", desc: "Supernatural allure, dread, and command of emotion." }),
  D({ key: "protean", name: "Protean", desc: "Shapeshifting and adaptation of the body." }),
  D({ key: "thinBloodAlchemy", name: "Thin-Blood Alchemy", desc: "The thin-blood's craft of distilling blood into potent formulae." }),
];

/* --- Powers ---------------------------------------------------------------
 * Every power listed on the wiki discipline pages, ordered by level within
 * each Discipline. `source` names the originating book (omitted for Corebook);
 * mechanical fields are functional summaries only.
 */
const powers = [
  // Animalism ---------------------------------------------------
  Power({ disc: "animalism", name: "Bond Famulus", level: 1, cost: "Two Rouse Checks", pool: "Charisma + Animal Ken", desc: "Bond a single animal as a loyal, empowered companion." }),
  Power({ disc: "animalism", name: "Sense the Beast", level: 1, cost: "Free", pool: "Resolve + Animalism", opp: "Composure + Subterfuge", desc: "Sense anger, hunger, and the supernatural Beast in those nearby." }),
  Power({ disc: "animalism", name: "Animal Messenger", level: 2, cost: "One Rouse Check per night", amalgam: AM("auspex", 1), source: "Players Guide", desc: "Send a bonded animal to carry a message and relay its senses." }),
  Power({ disc: "animalism", name: "Atavism", level: 2, cost: "One Rouse Check", pool: "Composure + Animalism", source: "Winter's Teeth", desc: "Drive a nearby animal into a fear or rage frenzy." }),
  Power({ disc: "animalism", name: "Feral Whispers", level: 2, cost: "One Rouse Check per type of animal", pool: "Manipulation/Charisma + Animalism", desc: "Communicate with animals and summon or command a species." }),
  Power({ disc: "animalism", name: "Leash the Beast", level: 2, cost: "One or Two Rouse Checks", amalgam: AM("fortitude", 1), source: "Live from the Succubus Club", desc: "Spend Blood to keep the Beast dormant and steady against frenzy." }),
  Power({ disc: "animalism", name: "Messenger's Command", level: 3, pool: "See Compel or Mesmerize", opp: "See Compel or Mesmerize", amalgam: AM("dominate", 1), source: "Players Guide", desc: "Route a Dominate compulsion through your bonded familiar to a target." }),
  Power({ disc: "animalism", name: "Animal Succulence", level: 3, cost: "Free", desc: "Draw far greater sustenance and satisfaction from feeding on animals." }),
  Power({ disc: "animalism", name: "Plague of Beasts", level: 3, cost: "One Rouse Check", pool: "Manipulation + Animalism", opp: "Composure + Animal Ken", source: "Players Guide", desc: "Mark a victim so ordinary animals hound, shun, and unsettle them." }),
  Power({ disc: "animalism", name: "Quell the Beast", level: 3, cost: "One Rouse Check", pool: "Charisma + Animalism", opp: "Stamina + Resolve", desc: "Smother a target's drives, ending frenzy or numbing them to apathy." }),
  Power({ disc: "animalism", name: "Scent of Prey", level: 3, cost: "One Rouse Check", pool: "Resolve + Animalism", source: "Sabbat", desc: "Catch the scent of mortals who witnessed a breach of the Masquerade." }),
  Power({ disc: "animalism", name: "Unliving Hive", level: 3, amalgam: AM("obfuscate", 2), desc: "House and command a swarm of vermin or insects within the body." }),
  Power({ disc: "animalism", name: "Augury", level: 3, cost: "One Rouse Check", pool: "Manipulation + Animalism", amalgam: AM("auspex", 1), source: "Tattered Façade", desc: "Compel a swarm of creatures to shape an answer to your question." }),
  Power({ disc: "animalism", name: "Awaken the Parasite", level: 3, cost: "One Rouse Check", pool: "Resolve + Animalism", opp: "Composure + Resolve or Stamina + Wits (If mortal)", source: "Tattered Façade", desc: "Rouse imagined insects inside a victim's body to torment them." }),
  Power({ disc: "animalism", name: "Subsume the Spirit", level: 4, cost: "One Rouse Check", pool: "Manipulation + Animalism", desc: "Possess an animal and pilot its body from afar." }),
  Power({ disc: "animalism", name: "Sway the Flock", level: 4, cost: "One or more Rouse Checks", pool: "Composure + Animalism", source: "Players Guide", desc: "Bend the mood and behavior of a whole group of animals at once." }),
  Power({ disc: "animalism", name: "Animal Dominion", level: 5, cost: "Two Rouse Checks", pool: "Charisma + Animalism", desc: "Take absolute command of a large group of animals at once." }),
  Power({ disc: "animalism", name: "Coax the Bestial Temper", level: 5, cost: "One Rouse Check", pool: "Manipulation + Animalism", source: "Players Guide", desc: "Raise or lower how easily nearby vampires slip into frenzy." }),
  Power({ disc: "animalism", name: "Drawing Out the Beast", level: 5, cost: "One Rouse Check", pool: "Wits + Animalism", opp: "Composure + Resolve", desc: "Cast one's own frenzy into a nearby victim, who rages in your place." }),
  Power({ disc: "animalism", name: "Spirit Walk", level: 5, source: "Gehenna War", desc: "Leap your possessing mind directly from one animal host to another." }),

  // Auspex ------------------------------------------------------
  Power({ disc: "auspex", name: "Heightened Senses", level: 1, cost: "Free", pool: "Wits + Resolve", desc: "Sharpen all senses to supernatural acuity." }),
  Power({ disc: "auspex", name: "Sense the Unseen", level: 1, cost: "Free", pool: "Wits/Resolve + Auspex", desc: "Detect the supernatural — the hidden, the cloaked, the spectral." }),
  Power({ disc: "auspex", name: "Panacea", level: 2, cost: "One Rouse Check", pool: "Composure + Auspex", amalgam: AM("fortitude", 1), source: "Companion", desc: "Soothe fear and frenzy in another and restore a little of their Willpower." }),
  Power({ disc: "auspex", name: "Premonition", level: 2, cost: "Free / One Rouse Check", pool: "Resolve + Auspex", desc: "Receive flashes of insight or warning about coming danger." }),
  Power({ disc: "auspex", name: "Reveal Temperament", level: 2, cost: "One Rouse Check", pool: "Intelligence + Auspex", opp: "Composure + Subterfuge", source: "Players Guide", desc: "Read the Resonance and temperament of blood or a mortal at a glance." }),
  Power({ disc: "auspex", name: "Unerring Pursuit", level: 2, cost: "One Rouse Check", pool: "Resolve + Auspex", amalgam: AM("dominate", 1), source: "Sabbat", desc: "Mark a target through a reflection to track and observe them at a distance." }),
  Power({ disc: "auspex", name: "Vermin Vision", level: 3, cost: "One Rouse Check", pool: "Resolve + Animalism Errata", amalgam: AM("animalism", 2), source: "Fall of London", desc: "Perceive the world through the senses of animals, even whole groups." }),
  Power({ disc: "auspex", name: "Fatal Flaw", level: 3, cost: "One Rouse Check", pool: "Intelligence + Auspex", opp: "Composure/Stamina + Subterfuge", amalgam: AM("oblivion", 1), source: "Players Guide", desc: "Discern a target's exploitable mental or physical weakness." }),
  Power({ disc: "auspex", name: "Scry the Soul", level: 3, cost: "One Rouse Check", pool: "Intelligence + Auspex", opp: "Composure + Subterfuge", desc: "Read a subject's aura to gauge mood, health, and supernatural nature." }),
  Power({ disc: "auspex", name: "Share the Senses", level: 3, cost: "One Rouse Check", pool: "Resolve + Auspex", desc: "Reach into another's senses and perceive what they perceive." }),
  Power({ disc: "auspex", name: "Haruspex", level: 3, cost: "One Rouse Check", pool: "Resolve + Auspex", amalgam: AM("oblivion", 1), source: "Tattered Façade", desc: "Read a fresh corpse to reroll dice later that same night." }),
  Power({ disc: "auspex", name: "Spirit's Touch", level: 4, cost: "One Rouse Check", pool: "Intelligence + Auspex", desc: "Read the psychic impressions left on an object by those who handled it." }),
  Power({ disc: "auspex", name: "Heart Laid Bare", level: 4, cost: "One Rouse Check", pool: "Intelligence + Auspex", opp: "Composure + Subterfuge", source: "Tattered Façade", desc: "Lay bare a target's deepest fear or truest desire." }),
  Power({ disc: "auspex", name: "Clairvoyance", level: 5, cost: "One Rouse Check", pool: "Intelligence + Auspex", desc: "Extend perception across a wide, familiar area to gather information." }),
  Power({ disc: "auspex", name: "Possession", level: 5, cost: "Two Rouse Checks", pool: "Resolve + Auspex", opp: "Resolve + Intelligence", amalgam: AM("dominate", 3), desc: "Project into and seize control of a mortal's body." }),
  Power({ disc: "auspex", name: "Telepathy", level: 5, cost: "One Rouse (one Willpower on non-consenting vampires)", pool: "Resolve + Auspex", opp: "Wits + Subterfuge", desc: "Read surface thoughts and project your own into another mind." }),
  Power({ disc: "auspex", name: "Unburdening the Bestial Soul", level: 5, cost: "Two Rouse checks, 1 Stain", pool: "Composure + Auspex", amalgam: AM("dominate", 3), source: "Companion", desc: "Ease another's Beast, mending Stains and aiding recovery from trauma." }),

  // Blood Sorcery -----------------------------------------------
  Power({ disc: "bloodSorcery", name: "Corrosive Vitae", level: 1, cost: "One or more Rouse Checks", desc: "Make your Vitae caustic, eating through matter it touches." }),
  Power({ disc: "bloodSorcery", name: "Shape the Sanguine Sacrament", level: 1, cost: "Free", pool: "Manipulation + Blood Sorcery", source: "Winter's Teeth", desc: "Shape spilled blood into images, shapes, or written messages." }),
  Power({ disc: "bloodSorcery", name: "A Taste for Blood", level: 1, cost: "Free", pool: "Resolve + Blood Sorcery", desc: "Learn traits about a victim — Resonance, Blood Potency, sickness — from a taste." }),
  Power({ disc: "bloodSorcery", name: "Koldunic Sorcery", level: 1, cost: "One Rouse Check and Aggravated Health Damage", pool: "Resolve + Blood Sorcery", opp: "Wits or Resolve + Obfuscate", source: "Blood Sigils", desc: "Bond with a chosen element to sense and perceive through it." }),
  Power({ disc: "bloodSorcery", name: "Blood's Curse", level: 2, cost: "One Rouse Check", pool: "Intelligence + Blood Sorcery", opp: "Stamina + Occult / Fortitude", source: "Gehenna War", desc: "Worsen another vampire's clan bane, or afflict the baneless with one." }),
  Power({ disc: "bloodSorcery", name: "Extinguish Vitae", level: 2, cost: "One Rouse Check", pool: "Intelligence + Blood Sorcery", opp: "Stamina + Composure", desc: "Raise a target's Hunger by burning away their Vitae." }),
  Power({ disc: "bloodSorcery", name: "Scour Secrets", level: 2, cost: "One Rouse Check", pool: "Intelligence + Blood Sorcery", source: "Players Guide", desc: "Read and absorb vast written material within mere minutes." }),
  Power({ disc: "bloodSorcery", name: "Blood of Potency", level: 3, cost: "One Rouse Check", pool: "Resolve + Blood Sorcery", desc: "Temporarily raise your own Blood Potency for a scene." }),
  Power({ disc: "bloodSorcery", name: "Scorpion's Touch", level: 3, cost: "One or more Rouse Checks", pool: "Strength + Blood Sorcery", opp: "Stamina + Occult/Fortitude", desc: "Turn your Vitae into a paralytic poison delivered by touch." }),
  Power({ disc: "bloodSorcery", name: "Transitive Bond", level: 3, cost: "One Rouse Check", source: "Sabbat", desc: "Carry the blood bond's hold through vitae passed between vessels." }),
  Power({ disc: "bloodSorcery", name: "Ripples of the Heart", level: 3, cost: "One Rouse Check", source: "Blood Stained Love", desc: "Taint blood to impose compulsions or reshape a mortal's Resonance." }),
  Power({ disc: "bloodSorcery", name: "Theft of Vitae", level: 4, cost: "One Rouse Check", pool: "Wits + Blood Sorcery", opp: "Wits + Occult", desc: "Draw a victim's blood to yourself across a distance in a crimson arc." }),
  Power({ disc: "bloodSorcery", name: "Blood Aegis", level: 4, cost: "One or more Rouse Checks", source: "Players Guide", desc: "Raise a shield of vitae that soaks incoming damage." }),
  Power({ disc: "bloodSorcery", name: "Fulminating Vitae", level: 4, cost: "Two Rouse Checks", pool: "Stamina + Blood Sorcery", opp: "Wits + Athletics", source: "Tattered Façade", desc: "Turn a jar of blood into a hurled explosive, searing Kindred." }),
  Power({ disc: "bloodSorcery", name: "Marionette", level: 4, cost: "One Rouse Checks", pool: "Manipulation + Blood Sorcery", opp: "Stamina + Occult or Fortitude", source: "Tattered Façade", desc: "Puppeteer a body, living or dead, by commanding its blood." }),
  Power({ disc: "bloodSorcery", name: "Baal's Caress", level: 5, cost: "One or more Rouse Checks", pool: "Strength + Blood Sorcery", opp: "Stamina + Occult/Fortitude", desc: "Coat a weapon in caustic Vitae that deals Aggravated damage." }),
  Power({ disc: "bloodSorcery", name: "Cauldron of Blood", level: 5, cost: "One Rouse Check, Stains", pool: "Resolve + Blood Sorcery", opp: "Composure + Occult/Fortitude", desc: "Boil a victim's blood in their veins, inflicting grievous Aggravated harm." }),
  Power({ disc: "bloodSorcery", name: "Reclamation of Vitae", level: 5, cost: "One or more Stains", source: "Sabbat", desc: "Draw back vitae fed to your ghouls across a distance." }),

  // Celerity ----------------------------------------------------
  Power({ disc: "celerity", name: "Cat's Grace", level: 1, cost: "Free", desc: "Automatically keep your balance on any surface." }),
  Power({ disc: "celerity", name: "Fluent Swiftness", level: 1, cost: "Free", source: "Gehenna War", desc: "Reroll the Blood Surge on Dexterity or Celerity rolls." }),
  Power({ disc: "celerity", name: "Rapid Reflexes", level: 1, cost: "Free", desc: "React with supernatural speed, ignoring penalties for hasty action." }),
  Power({ disc: "celerity", name: "Fleetness", level: 2, cost: "One Rouse Check", desc: "Add Celerity dice to Dexterity rolls and move at blurring speed." }),
  Power({ disc: "celerity", name: "Rush Job", level: 2, cost: "One Rouse Check", source: "Players Guide", desc: "Perform a time-consuming manual task in a fraction of the time." }),
  Power({ disc: "celerity", name: "Blink", level: 3, cost: "One Rouse Check", pool: "Dexterity + Athletics", desc: "Cover a short distance almost instantly in a single surge." }),
  Power({ disc: "celerity", name: "Traversal", level: 3, cost: "One Rouse Check", pool: "Dexterity + Athletics", desc: "Run across water or up sheer surfaces for as long as your speed holds." }),
  Power({ disc: "celerity", name: "Weaving", level: 3, cost: "One Rouse Check", source: "Players Guide", desc: "Dodge with preternatural fluidity, adding Celerity to defense against attacks." }),
  Power({ disc: "celerity", name: "A Thousand Cuts", level: 3, cost: "One Rouse Check", source: "Tattered Façade", desc: "Blur-fast claw or blade strikes cripple mortals and expose Kindred." }),
  Power({ disc: "celerity", name: "Blurred Momentum", level: 4, cost: "One Rouse Check per turn", source: "Players Guide", desc: "Move so fast that weak attacks against you simply miss." }),
  Power({ disc: "celerity", name: "Draught of Elegance", level: 4, cost: "One Rouse Check", desc: "Grant your supernatural speed to another by feeding them your Vitae." }),
  Power({ disc: "celerity", name: "Unerring Aim", level: 4, cost: "One Rouse Check", amalgam: AM("auspex", 2), desc: "Perceive slowly enough to land a ranged attack with pinpoint accuracy." }),
  Power({ disc: "celerity", name: "Unseen Strike", level: 4, cost: "Two Rouse Checks", pool: "Dexterity + Celerity", opp: "Wits + Awareness", amalgam: AM("obfuscate", 4), source: "Players Guide", desc: "Strike from concealment at blurring speed as an undodgeable ambush." }),
  Power({ disc: "celerity", name: "Faster than Light", level: 4, cost: "One Rouse Check", source: "Live from the Succubus Club", desc: "While blinking, dash through sunlight or fire unharmed by the passage." }),
  Power({ disc: "celerity", name: "Lightning Strike", level: 5, cost: "One Rouse Check", desc: "Attack first with unstoppable speed, striking before foes can react." }),
  Power({ disc: "celerity", name: "Split Second", level: 5, cost: "One Rouse Check", desc: "Bend the moment to perform one impossible action in the nick of time." }),

  // Dominate ----------------------------------------------------
  Power({ disc: "dominate", name: "Cloud Memory", level: 1, cost: "Free", pool: "Charisma + Dominate", opp: "Wits + Resolve", desc: "Erase a victim's memory of the past few moments." }),
  Power({ disc: "dominate", name: "Compel", level: 1, cost: "Free", pool: "Charisma + Dominate", opp: "Intelligence + Resolve", desc: "Issue a single short command a victim obeys at once." }),
  Power({ disc: "dominate", name: "Slavish Devotion", level: 1, cost: "Free", amalgam: AM("fortitude", 1), source: "Cults of the Blood Gods", desc: "Harden your thralls' minds against the influence of anyone but you." }),
  Power({ disc: "dominate", name: "Mesmerize", level: 2, cost: "One Rouse Check", pool: "Manipulation + Dominate", opp: "Intelligence + Resolve", desc: "Implant a more complex, multi-step command in a victim's mind." }),
  Power({ disc: "dominate", name: "Dementation", level: 2, cost: "One Rouse Check per target per Scene", pool: "Manipulation + Dominate", opp: "Composure + Intelligence", amalgam: AM("obfuscate", 2), desc: "Stir madness, panic, and emotional turmoil in a target." }),
  Power({ disc: "dominate", name: "Domitor's Favor", level: 2, cost: "One Rouse Check", source: "Companion", desc: "Make blood-bonded thralls find it far harder to defy your orders." }),
  Power({ disc: "dominate", name: "The Stolen Voice", level: 2, cost: "One Rouse Check", pool: "Composure + Dominate", opp: "Resolve + Performance", source: "Tattered Façade", desc: "Strip a target's ability to speak, write, or gesture meaning." }),
  Power({ disc: "dominate", name: "Forgetful Mind", level: 3, cost: "One Rouse Check", pool: "Manipulation + Dominate", opp: "Intelligence + Resolve", desc: "Rewrite or fabricate a victim's memories wholesale." }),
  Power({ disc: "dominate", name: "Submerged Directive", level: 3, cost: "Free", desc: "Plant a dormant Mesmerize command that triggers on a set stimulus." }),
  Power({ disc: "dominate", name: "Ancestral Dominion", level: 4, cost: "One Rouse Check", pool: "Manipulation + Dominate", opp: "Resolve + Occult Errata", amalgam: AM("bloodSorcery", 2), source: "Cults of the Blood Gods", desc: "Command your own blood-descendants without word or eye contact." }),
  Power({ disc: "dominate", name: "Implant Suggestion", level: 4, cost: "One Rouse Check", pool: "Manipulation + Dominate", opp: "Composure + Resolve", amalgam: AM("presence", 1), source: "Players Guide", desc: "Temporarily rewrite a target's opinion or personality to your liking." }),
  Power({ disc: "dominate", name: "Rationalize", level: 4, cost: "Free", desc: "Make dominated victims believe their compelled acts were their own choice." }),
  Power({ disc: "dominate", name: "Tabula Rasa", level: 4, cost: "Two Rouse Checks", pool: "Resolve + Dominate", opp: "Composure + Resolve", source: "Sabbat", desc: "Strip a mind bare, leaving a blank, pliant slate." }),
  Power({ disc: "dominate", name: "Lethe's Call", level: 5, cost: "One Rouse Check", pool: "Manipulation + Dominate", opp: "Intelligence + Resolve", source: "Gehenna War", desc: "Wipe away weeks of a target's recent memories." }),
  Power({ disc: "dominate", name: "Mass Manipulation", level: 5, cost: "One Rouse Check in addition to power it's added to", desc: "Extend a Dominate power to affect an entire crowd at once." }),
  Power({ disc: "dominate", name: "Terminal Decree", level: 5, cost: "Free but will give Stains", desc: "Command victims to acts of self-harm they would normally refuse." }),

  // Fortitude ---------------------------------------------------
  Power({ disc: "fortitude", name: "Fluent Endurance", level: 1, cost: "Free", source: "Gehenna War", desc: "Retry the Blood Surge rouse check on Stamina or Fortitude efforts." }),
  Power({ disc: "fortitude", name: "Resilience", level: 1, cost: "Free", desc: "Add Fortitude dice to resist and soak physical damage." }),
  Power({ disc: "fortitude", name: "Unswayable Mind", level: 1, cost: "Free", desc: "Bolster resistance against mental influence and coercion." }),
  Power({ disc: "fortitude", name: "Earth's Perseverance", level: 2, cost: "One Rouse Check", source: "Players Guide", desc: "Root yourself in place, immovable by any force applied." }),
  Power({ disc: "fortitude", name: "Enduring Beasts", level: 2, cost: "One Rouse Check", pool: "Stamina + Animalism", amalgam: AM("animalism", 1), desc: "Extend your durability to animals under your command." }),
  Power({ disc: "fortitude", name: "Invigorating Vitae", level: 2, cost: "None other than the Rouse Checks to give Blood", amalgam: AM("auspex", 1), source: "Players Guide", desc: "Speed a mortal's healing by feeding them your blood." }),
  Power({ disc: "fortitude", name: "Obdurate", level: 2, cost: "One Rouse Check", pool: "Wits + Survival", amalgam: AM("potence", 2), source: "Winter's Teeth", desc: "Plant your feet and shrug off knockdown and forced movement." }),
  Power({ disc: "fortitude", name: "Toughness", level: 2, cost: "One Rouse Check", desc: "Subtract Fortitude rating from Superficial physical damage taken." }),
  Power({ disc: "fortitude", name: "Self-Assurance", level: 2, cost: "One Rouse Check", source: "Live from the Succubus Club", desc: "Blunt Willpower damage suffered during social clashes by your Fortitude." }),
  Power({ disc: "fortitude", name: "Defy Bane", level: 3, cost: "One Rouse Check", pool: "Wits + Survival", desc: "Steel yourself to resist a source of Aggravated damage for a moment." }),
  Power({ disc: "fortitude", name: "Fortify the Inner Façade", level: 3, cost: "Free", desc: "Resist Auspex and other attempts to read your thoughts or aura." }),
  Power({ disc: "fortitude", name: "Seal the Beast's Maw", level: 3, cost: "Two Rouse Checks", source: "Forbidden Religions", desc: "Suppress your own Hunger for a time, holding the Beast at bay." }),
  Power({ disc: "fortitude", name: "Valeren", level: 3, cost: "One Rouse Check", pool: "Intelligence + Fortitude", amalgam: AM("auspex", 1), source: "Companion", desc: "Channel vitae to knit an injured vampire's wounds closed." }),
  Power({ disc: "fortitude", name: "Calloused Soul", level: 3, cost: "Two stains", source: "Tattered Façade", desc: "Take stains ahead of time to soften later stains inflicted." }),
  Power({ disc: "fortitude", name: "Draught of Endurance", level: 4, cost: "One Rouse Check + Drinkers", desc: "Grant your toughness to another by feeding them your Vitae." }),
  Power({ disc: "fortitude", name: "Gorgon's Scales", level: 4, cost: "One Rouse Check", source: "Players Guide", desc: "Draw resistances from your blood's Resonance against stakes, fire, or sun." }),
  Power({ disc: "fortitude", name: "Shatter", level: 4, cost: "One Rouse Check", source: "Cults of the Blood Gods", desc: "Turn your resilience outward, hurling absorbed damage back and breaking weapons." }),
  Power({ disc: "fortitude", name: "Flesh of Marble", level: 5, cost: "Two Rouse Checks", desc: "Turn your flesh nigh-impervious, ignoring the first source of damage each turn." }),
  Power({ disc: "fortitude", name: "Prowess from Pain", level: 5, cost: "One Rouse Check", desc: "Convert incoming injury into surges of physical might." }),
  Power({ disc: "fortitude", name: "Meat Shields", level: 5, cost: "One Rouse Check", source: "Tattered Façade", desc: "Bolster Fortitude using the frail mortals gathered around you." }),

  // Obfuscate ---------------------------------------------------
  Power({ disc: "obfuscate", name: "Cloak of Shadows", level: 1, cost: "Free", desc: "Blend into surroundings and go unnoticed while still and hidden." }),
  Power({ disc: "obfuscate", name: "Ensconce", level: 1, cost: "Free", source: "Gehenna War", desc: "Hide a small object on your person from sight and search." }),
  Power({ disc: "obfuscate", name: "Silence of Death", level: 1, cost: "Free", desc: "Mute all sound you make, moving in perfect quiet." }),
  Power({ disc: "obfuscate", name: "Mask of Ages", level: 1, cost: "One Rouse Check", source: "Live from the Succubus Club", desc: "Alter your apparent age, seeming decades older or younger than you are." }),
  Power({ disc: "obfuscate", name: "Cache", level: 2, cost: "One Rouse Check", source: "Gehenna War", desc: "Cloak unattended objects from sight, keeping them hidden from onlookers." }),
  Power({ disc: "obfuscate", name: "Chimerstry", level: 2, cost: "One Rouse Check", pool: "Manipulation + Obfuscate", opp: "Composure + Wits", amalgam: AM("presence", 1), source: "Companion", desc: "Conjure a fleeting but convincing illusion that fools the senses briefly." }),
  Power({ disc: "obfuscate", name: "Ghost's Passing", level: 2, cost: "One Rouse Check", amalgam: AM("animalism", 1), source: "Forbidden Religions", desc: "Cloak an animal's trail so trackers cannot follow its passage." }),
  Power({ disc: "obfuscate", name: "Unseen Passage", level: 2, cost: "One Rouse Check", desc: "Remain unseen even while moving through an area." }),
  Power({ disc: "obfuscate", name: "Ventriloquism", level: 2, cost: "One Rouse Check", pool: "Wits + Obfuscate", opp: "Resolve + Composure", amalgam: AM("auspex", 2), source: "Fall of London", desc: "Cast your voice so only your chosen listener hears the words." }),
  Power({ disc: "obfuscate", name: "Doubletalk", level: 2, cost: "One Rouse Check", pool: "Composure + Obfuscate", opp: "Wits + Auspex", amalgam: AM("auspex", 1), source: "Blood Stained Love", desc: "Speak openly while slipping a hidden message to one listener." }),
  Power({ disc: "obfuscate", name: "Fata Morgana", level: 3, cost: "One Rouse Check", pool: "Manipulation + Obfuscate", amalgam: AM("presence", 2), source: "Companion", desc: "Weave an elaborate but static illusion for others to perceive." }),
  Power({ disc: "obfuscate", name: "Ghost in the Machine", level: 3, cost: "Free", desc: "Extend your concealment to fool cameras and recording devices." }),
  Power({ disc: "obfuscate", name: "Mask of a Thousand Faces", level: 3, cost: "One Rouse Check", desc: "Wear an unremarkable, forgettable false face of your design." }),
  Power({ disc: "obfuscate", name: "Mask of Isolation", level: 3, cost: "One Rouse Check", pool: "Manipulation + Obfuscate", opp: "Charisma + Insight", amalgam: AM("dominate", 1), source: "Sabbat", desc: "Impose a false face on a victim, trapping them behind it." }),
  Power({ disc: "obfuscate", name: "Mental Maze", level: 3, cost: "One or Three Rouse Checks", pool: "Charisma + Obfuscate", opp: "Wits + Resolve", amalgam: AM("dominate", 1), source: "Cults of the Blood Gods", desc: "Meet a victim's eyes and strip away all sense of direction." }),
  Power({ disc: "obfuscate", name: "Mind Masque", level: 3, cost: "One Rouse Check", pool: "Intelligence + Obfuscate", amalgam: AM("dominate", 2), source: "Players Guide", desc: "Cloak your true thoughts and feelings from supernatural mind-reading." }),
  Power({ disc: "obfuscate", name: "Guise of the Departed", level: 3, cost: "One Rouse Check", pool: "Wits + Obfuscate", amalgam: AM("oblivion", 1), source: "Tattered Façade", desc: "Wear the face and manner of someone who recently died." }),
  Power({ disc: "obfuscate", name: "Conceal", level: 4, cost: "One Rouse Check", pool: "Intelligence + Obfuscate", amalgam: AM("auspex", 3), desc: "Hide an inanimate object, a vehicle, or even a small building." }),
  Power({ disc: "obfuscate", name: "Vanish", level: 4, cost: "As per power augmented", pool: "Wits + Obfuscate", opp: "Wits + Awareness", desc: "Disappear from plain sight even while being actively watched." }),
  Power({ disc: "obfuscate", name: "Seclusion", level: 4, cost: "One Rouse check", pool: "Manipulation + Obfuscate", opp: "Resolve + Awareness", amalgam: AM("dominate", 1), source: "Tattered Façade", desc: "Cut a target off entirely, blind and deaf to everyone around them." }),
  Power({ disc: "obfuscate", name: "Cloak the Gathering", level: 5, cost: "One Rouse Check in addition to the cost of the power extended", desc: "Extend your concealment to a group of companions." }),
  Power({ disc: "obfuscate", name: "Impostor's Guise", level: 5, cost: "One Rouse Check", pool: "Wits + Obfuscate", opp: "Manipulation + Performance", desc: "Perfectly copy the face and voice of a specific person you have studied." }),

  // Oblivion ----------------------------------------------------
  Power({ disc: "oblivion", name: "Ashes to Ashes", level: 1, cost: "One Rouse Check", pool: "Stamina + Oblivion", opp: "Stamina + Medicine/Fortitude", source: "Cults of the Blood Gods", desc: "Dissolve a corpse into nothing, erasing the body from existence." }),
  Power({ disc: "oblivion", name: "Binding Fetter", level: 1, cost: "Free", pool: "Wits + Oblivion Errata", source: "Cults of the Blood Gods", desc: "Sense which nearby objects anchor a ghost to the living world." }),
  Power({ disc: "oblivion", name: "Oblivion Sight", level: 1, cost: "Free", source: "Chicago by Night", desc: "See in total darkness and glimpse the presence of the dead." }),
  Power({ disc: "oblivion", name: "Shadow Cloak", level: 1, cost: "Free", source: "Chicago by Night", desc: "Wrap yourself in shadow to intimidate or hide in darkness." }),
  Power({ disc: "oblivion", name: "Arms of Ahriman", level: 2, cost: "One Rouse Check", pool: "Wits + Oblivion", amalgam: AM("potence", 2), source: "Chicago by Night", desc: "Grow grasping tendrils of shadow to seize and crush at a distance." }),
  Power({ disc: "oblivion", name: "Fatal Prediction", level: 2, cost: "One Rouse Check", pool: "Resolve + Oblivion", opp: "Wits + Occult", amalgam: AM("auspex", 2), source: "Players Guide", desc: "Curse a mortal so accidents and mishaps wound them from afar." }),
  Power({ disc: "oblivion", name: "Fatal Precognition", level: 2, cost: "One Rouse Check", pool: "Resolve + Oblivion", amalgam: AM("auspex", 2), source: "Cults of the Blood Gods", desc: "Glimpse a vision foretelling how a mortal target will die." }),
  Power({ disc: "oblivion", name: "Shadow Cast", level: 2, cost: "One Rouse Check", source: "Chicago by Night", desc: "Summon and shape a pool of unnatural shadow you command." }),
  Power({ disc: "oblivion", name: "Where the Veil Thins", level: 2, cost: "One Rouse Check", pool: "Intelligence + Oblivion Errata", source: "Cults of the Blood Gods", desc: "Gauge how thick or thin the Shroud is around you." }),
  Power({ disc: "oblivion", name: "Aura of Decay", level: 3, cost: "One Rouse Check", pool: "Stamina + Oblivion", opp: "Stamina + Medicine/Fortitude", source: "Cults of the Blood Gods", desc: "Radiate rot that spoils food, sickens the living, and ages objects." }),
  Power({ disc: "oblivion", name: "Passion Feast", level: 3, cost: "Free", pool: "Resolve + Oblivion", opp: "Resolve + Composure", amalgam: AM("fortitude", 2), source: "Cults of the Blood Gods", desc: "Sate your Hunger by devouring the raw passions of nearby wraiths." }),
  Power({ disc: "oblivion", name: "Shadow Perspective", level: 3, cost: "One Rouse Check", source: "Chicago by Night", desc: "Project your senses through a distant patch of shadow." }),
  Power({ disc: "oblivion", name: "Shadow Servant", level: 3, cost: "One Rouse Check", amalgam: AM("auspex", 1), source: "Players Guide", desc: "Animate a mindless shadow to scout ahead or frighten your enemies." }),
  Power({ disc: "oblivion", name: "Touch of Oblivion", level: 3, cost: "One Rouse Check", source: "Chicago by Night", desc: "Wither and decay a limb or organ with a single touch." }),
  Power({ disc: "oblivion", name: "Necrotic Plague", level: 4, cost: "One Rouse Check Errata", pool: "Intelligence + Oblivion", opp: "Stamina + Medicine/Fortitude", source: "Cults of the Blood Gods", desc: "Afflict a mortal with a lingering supernatural wasting sickness." }),
  Power({ disc: "oblivion", name: "Profane the Sanctified", level: 4, cost: "One Rouse Check", pool: "Resolve + Oblivion", opp: "Willpower Test", source: "Tattered Façade", desc: "Stun the faithful, cancel their True Faith, and rot holy relics." }),
  Power({ disc: "oblivion", name: "Stygian Shroud", level: 4, cost: "One Rouse Check", source: "Chicago by Night", desc: "Unleash smothering darkness that blinds and chokes those within." }),
  Power({ disc: "oblivion", name: "Umbrous Clutch", level: 4, cost: "One Rouse Check, One Stain", pool: "Wits + Oblivion", opp: "Dexterity + Wits", source: "Sabbat", desc: "Use a victim's own shadow as a gate to seize and drag them." }),
  Power({ disc: "oblivion", name: "The Darkness Within", level: 5, cost: "Two Rouse Checks", pool: "Manipulation + Oblivion", opp: "Composure + Resolve", source: "Tattered Façade", desc: "Draw a murderous dark double out of a victim to attack them." }),
  Power({ disc: "oblivion", name: "Shadow Step", level: 5, cost: "One Rouse Check", source: "Chicago by Night", desc: "Step into one shadow and emerge from another nearby." }),
  Power({ disc: "oblivion", name: "Skuld Fulfilled", level: 5, cost: "Two Rouse Checks", pool: "Stamina + Oblivion", opp: "Stamina + Stamina/Fortitude Errata", source: "Cults of the Blood Gods", desc: "Reawaken a disease a target had already recovered from." }),
  Power({ disc: "oblivion", name: "Tenebrous Avatar", level: 5, cost: "Two Rouse Checks", source: "Chicago by Night", desc: "Become living shadow, flowing and near-untouchable." }),
  Power({ disc: "oblivion", name: "Withering Spirit", level: 5, cost: "Two Rouse Checks, Stains", pool: "Resolve + Oblivion", opp: "Resolve + Occult/Fortitude", source: "Cults of the Blood Gods", desc: "Attack and erode a victim's very soul and will." }),

  // Potence -----------------------------------------------------
  Power({ disc: "potence", name: "Fluent Strength", level: 1, cost: "Free", source: "Gehenna War", desc: "Reroll the Blood Surge rouse check on Strength or Potence rolls." }),
  Power({ disc: "potence", name: "Lethal Body", level: 1, cost: "Free", desc: "Make unarmed strikes deal serious, even Aggravated, damage." }),
  Power({ disc: "potence", name: "Soaring Leap", level: 1, cost: "Free", desc: "Jump extraordinary distances up, across, or down." }),
  Power({ disc: "potence", name: "Prowess", level: 2, cost: "One Rouse Check", desc: "Add Potence dice to feats of Strength and melee damage." }),
  Power({ disc: "potence", name: "Relentless Grasp", level: 2, cost: "One Rouse Check", source: "Players Guide", desc: "Lock an unbreakable grip on a foe, weapon, or handhold." }),
  Power({ disc: "potence", name: "Brutal Feed", level: 3, cost: "Free", desc: "Drain a victim of all their blood in a matter of seconds." }),
  Power({ disc: "potence", name: "Exuberance", level: 3, cost: "Free", source: "Tattered Façade", desc: "Treat your Potence as two dots higher, risking backlash damage." }),
  Power({ disc: "potence", name: "Spark of Rage", level: 3, cost: "One Rouse Check", amalgam: AM("presence", 3), desc: "Provoke anger and violence in a crowd or individual." }),
  Power({ disc: "potence", name: "Uncanny Grip", level: 3, cost: "One Rouse Check", desc: "Cling to and crush surfaces, hanging from walls or ceilings." }),
  Power({ disc: "potence", name: "Wrecker", level: 3, cost: "Free", source: "Players Guide", desc: "Double your effective Strength for feats of raw destruction." }),
  Power({ disc: "potence", name: "Draught of Might", level: 4, cost: "One Rouse Check", desc: "Grant your supernatural strength to another via your Vitae." }),
  Power({ disc: "potence", name: "Crash Down", level: 4, cost: "One Rouse Check", pool: "Strength + Potence", opp: "Dexterity + Athletics", source: "Players Guide", desc: "Land from a mighty leap to batter and floor nearby foes." }),
  Power({ disc: "potence", name: "Earth Shock", level: 5, cost: "Two Rouse Checks", desc: "Strike the ground to loose a shockwave that fells those nearby." }),
  Power({ disc: "potence", name: "Fist of Caine", level: 5, cost: "One Rouse Check", desc: "Deliver a devastating blow of unstoppable, tearing force." }),
  Power({ disc: "potence", name: "Subtle Hammer", level: 5, cost: "Free", source: "Players Guide", desc: "Focus your crushing strength into a single targeted body part." }),

  // Presence ----------------------------------------------------
  Power({ disc: "presence", name: "Awe", level: 1, cost: "Free", desc: "Become magnetically attractive and persuasive to those around you." }),
  Power({ disc: "presence", name: "Daunt", level: 1, cost: "Free", desc: "Radiate menace, pushing others to leave you be or back down." }),
  Power({ disc: "presence", name: "Eyes of the Serpent", level: 1, cost: "Free", pool: "Charisma + Presence", opp: "Wits + Composure", amalgam: AM("protean", 1), source: "Anarch", desc: "Hold a victim transfixed and immobile while they meet your gaze." }),
  Power({ disc: "presence", name: "Lingering Kiss", level: 2, cost: "Free", desc: "Make the euphoria of your bite intoxicating and memorable to mortals." }),
  Power({ disc: "presence", name: "Melpominee", level: 2, cost: "Free", source: "Players Guide", desc: "Project your Presence through song to reach far or scattered listeners." }),
  Power({ disc: "presence", name: "Clear the Field", level: 3, cost: "One Rouse Check", pool: "Composure + Presence", opp: "Wits + Composure", amalgam: AM("dominate", 3), source: "Fall of London", desc: "Empty a space calmly, sparing a chosen few from leaving." }),
  Power({ disc: "presence", name: "Dread Gaze", level: 3, cost: "One Rouse Check", pool: "Charisma + Presence", opp: "Composure + Resolve", desc: "Terrify a single victim into flight or paralysis with a look." }),
  Power({ disc: "presence", name: "Entrancement", level: 3, cost: "One Rouse Check", pool: "Charisma + Presence", opp: "Composure + Wits", desc: "Bind a victim into infatuated devotion for a time." }),
  Power({ disc: "presence", name: "Passion Leech", level: 3, cost: "One Rouse Check", pool: "Composure + Auspex", amalgam: AM("auspex", 2), source: "Tattered Façade", desc: "Drain a mortal's passion to briefly enjoy high Humanity's graces." }),
  Power({ disc: "presence", name: "Thrown Voice", level: 3, cost: "One Rouse Check", amalgam: AM("auspex", 1), source: "Players Guide", desc: "Cast your voice to any visible point and leave it lingering." }),
  Power({ disc: "presence", name: "True Love's Face", level: 3, cost: "One Rouse Check", pool: "Manipulation + Presence", opp: "Composure + Wits", amalgam: AM("obfuscate", 3), source: "Cults of the Blood Gods", desc: "Make a victim mistake you for someone they deeply love or hate." }),
  Power({ disc: "presence", name: "Invigorating Display", level: 3, cost: "One Rouse Check", pool: "Composure + Presence", source: "Live from the Succubus Club", desc: "Breathe in a worked crowd's energy to gain a fleeting Resonance." }),
  Power({ disc: "presence", name: "Inflame Desire", level: 4, cost: "One Rouse Check", pool: "Manipulation + Presence", opp: "Composure + Resolve", amalgam: AM("obfuscate", 1), source: "Tattered Façade", desc: "Amplify a victim's craving until they pursue nothing but satisfying it." }),
  Power({ disc: "presence", name: "Irresistible Voice", level: 4, cost: "No additional cost", amalgam: AM("dominate", 1), desc: "Make your spoken Dominate commands need only your voice to land." }),
  Power({ disc: "presence", name: "Magnum Opus", level: 4, cost: "One or more Rouse Checks", pool: "Charisma/Manipulation + Craft", amalgam: AM("auspex", 3), source: "Winter's Teeth", desc: "Imbue artwork with Presence so viewers fall under its sway." }),
  Power({ disc: "presence", name: "Suffuse the Edifice", level: 4, pool: "As power transmitted", opp: "As power transmitted", source: "Players Guide", desc: "Steep an entire building in your Presence to affect those inside." }),
  Power({ disc: "presence", name: "Summon", level: 4, cost: "One Rouse Check", pool: "Manipulation + Presence", opp: "Composure + Intelligence", desc: "Call a person you have touched with Presence to come to you." }),
  Power({ disc: "presence", name: "Wingman", level: 4, cost: "One Rouse Check plus additional powers", source: "Blood Stained Love", desc: "Channel your Presence through an ally for them to wield." }),
  Power({ disc: "presence", name: "Majesty", level: 5, cost: "Two Rouse Checks", pool: "Charisma + Presence", opp: "Composure + Resolve", desc: "Command such awe and dread that none dare act against you." }),
  Power({ disc: "presence", name: "Star Magnetism", level: 5, cost: "One additional Rouse Check", desc: "Project your Presence through cameras, screens, and broadcasts." }),

  // Protean -----------------------------------------------------
  Power({ disc: "protean", name: "Eyes of the Beast", level: 1, cost: "Free", desc: "See perfectly in total darkness with the Beast's red gaze." }),
  Power({ disc: "protean", name: "Squirm", level: 1, cost: "Free or One Rouse Check", source: "Tattered Façade", desc: "Soften flesh and bone to slip through cracks and narrow gaps." }),
  Power({ disc: "protean", name: "Weight of the Feather", level: 1, cost: "Free", pool: "Wits + Survival", desc: "Make yourself weightless to avoid falls and pressure triggers." }),
  Power({ disc: "protean", name: "Feral Weapons", level: 2, cost: "One Rouse Check", desc: "Grow claws or fangs that deal Aggravated damage." }),
  Power({ disc: "protean", name: "Vicissitude", level: 2, cost: "One Rouse Check", pool: "Resolve + Protean", amalgam: AM("dominate", 2), source: "Companion", desc: "Sculpt your own flesh and bone into new, grotesque configurations." }),
  Power({ disc: "protean", name: "Serpent's Kiss", level: 2, cost: "One Rouse Check", source: "Blood Stained Love", desc: "While biting, pump your own vitae into your victim's body." }),
  Power({ disc: "protean", name: "The False Sip", level: 2, cost: "One Rouse Check", amalgam: AM("fortitude", 1), source: "Blood Stained Love", desc: "Block ingested blood from absorbing, holding it to be spat out." }),
  Power({ disc: "protean", name: "Earth Meld", level: 3, cost: "One Rouse Check", desc: "Sink into and rest within bare, natural earth." }),
  Power({ disc: "protean", name: "Fleshcrafting", level: 3, cost: "One Rouse Check", pool: "Resolve + Protean", opp: "Stamina + Resolve", amalgam: AM("dominate", 2), source: "Companion", desc: "Reshape the flesh and features of another living or unliving body." }),
  Power({ disc: "protean", name: "Shapechange", level: 3, cost: "One Rouse Check", desc: "Take the form of a human-sized animal such as a wolf." }),
  Power({ disc: "protean", name: "Visceral Absorption", level: 3, cost: "One Rouse Check", pool: "Strength + Protean", amalgam: AM("bloodSorcery", 2), source: "Sabbat", desc: "Soak up spilled blood and bodily remains to scrub a scene clean." }),
  Power({ disc: "protean", name: "Masque of Death", level: 3, cost: "One Rouse Check", amalgam: AM("oblivion", 2), source: "Live from the Succubus Club", desc: "Feign a corpse, immobile but harmed only by aggravated damage." }),
  Power({ disc: "protean", name: "Horrid Form", level: 4, cost: "One Rouse Check", amalgam: AM("dominate", 2), source: "Companion", desc: "Twist into a towering, monstrous war-form built for slaughter." }),
  Power({ disc: "protean", name: "Metamorphosis", level: 4, cost: "One Rouse Check", desc: "Assume the shape of a smaller creature like a bat or a rat." }),
  Power({ disc: "protean", name: "Blood Form", level: 5, cost: "One Rouse Check", amalgam: AM("bloodSorcery", 2), source: "Gehenna War", desc: "Melt into a formless pool of blood that can flow freely." }),
  Power({ disc: "protean", name: "The Heart of Darkness", level: 5, cost: "Free", amalgam: AM("fortitude", 2), source: "Cults of the Blood Gods", desc: "Tear out your own heart and hide it safely elsewhere." }),
  Power({ disc: "protean", name: "Master of Forms", level: 5, cost: "None, but rouse for Shapechange as normal.", source: "Gehenna War", desc: "Shift into any animal shape rather than a single fixed one." }),
  Power({ disc: "protean", name: "Mist Form", level: 5, cost: "One to three Rouse Checks", desc: "Dissolve into a cloud of mist that drifts through the smallest gaps." }),
  Power({ disc: "protean", name: "One with the Land", level: 5, cost: "Two Rouse Checks", amalgam: AM("animalism", 2), source: "Companion", desc: "Meld into a wide stretch of your home territory and sense all within it." }),
  Power({ disc: "protean", name: "Swarm", level: 5, cost: "Two Rouse Checks", source: "Tattered Façade", desc: "Dissolve into a teeming swarm of insects or crawling vermin." }),
  Power({ disc: "protean", name: "The Unfettered Heart", level: 5, cost: "Free", desc: "Move your heart within your body, foiling a staking blow." }),
  Power({ disc: "protean", name: "Face of the Victim", level: 5, cost: "One Rouse Check", source: "Live from the Succubus Club", desc: "Take on the appearance of the last person you fed upon." }),

  // Thin-Blood Alchemy ------------------------------------------
  Power({ disc: "thinBloodAlchemy", name: "Body Paint", level: 1, cost: "One Rouse Check", pool: "Dexterity + Craft", source: "Blood Sigils", desc: "Distillate: brand living skin with customizable tattoos beyond ordinary ink." }),
  Power({ disc: "thinBloodAlchemy", name: "Checkout Time", level: 1, cost: "One Rouse Check", source: "Blood Sigils", desc: "Distillate: sink into a corpse-like torpor undetectable and immune to banes." }),
  Power({ disc: "thinBloodAlchemy", name: "Elevate", level: 1, cost: "One Rouse Check", pool: "Stamina + Alchemy", source: "Blood Sigils", desc: "Distillate: get high and, if well brewed, temporarily sharpen your Dexterity." }),
  Power({ disc: "thinBloodAlchemy", name: "Far Reach", level: 1, cost: "One Rouse Check", pool: "Resolve + Alchemy", opp: "Strength + Athletics", desc: "Distillate: grip and move objects at a distance by force of will." }),
  Power({ disc: "thinBloodAlchemy", name: "Food Stain", level: 1, cost: "One Rouse Check", source: "Blood Sigils", desc: "Distillate: tag a mortal so their later feeders stand out to you." }),
  Power({ disc: "thinBloodAlchemy", name: "Gaoler's Bane", level: 1, cost: "One Rouse Check", source: "Winter's Teeth", desc: "Distillate: gain a bonus to break free of bonds and grapples." }),
  Power({ disc: "thinBloodAlchemy", name: "Haze", level: 1, cost: "One Rouse Check", desc: "Distillate: conjure a concealing bank of fog around yourself." }),
  Power({ disc: "thinBloodAlchemy", name: "Mercurian Tongue", level: 1, cost: "One Rouse Check", source: "Players Guide", desc: "Distillate: speak a foreign language, swappable by feeding on another person." }),
  Power({ disc: "thinBloodAlchemy", name: "Plug-In", level: 1, cost: "One Rouse Check", pool: "Resolve + Alchemy", source: "Players Guide", desc: "Distillate: emit a weak electrical current through touch while contact holds." }),
  Power({ disc: "thinBloodAlchemy", name: "Portable Shade", level: 1, cost: "One Rouse Check", pool: "Stamina + Alchemy", source: "Sabbat", desc: "Distillate: endure sunlight and walk unharmed under the daytime sun." }),
  Power({ disc: "thinBloodAlchemy", name: "Speak From the Heart", level: 1, cost: "One Rouse Check", source: "Blood Sigils", desc: "Distillate: embed a message in someone's blood for their next drinker." }),
  Power({ disc: "thinBloodAlchemy", name: "Advanced Torpor", level: 2, cost: "One Rouse Check", source: "Blood Sigils", desc: "Distillate: drop instantly into torpor while healing as a full vampire." }),
  Power({ disc: "thinBloodAlchemy", name: "Blacklight Surprise", level: 2, cost: "One Rouse Check", source: "Blood Sigils", desc: "Distillate: make ultraviolet light burn vampires like sunlight." }),
  Power({ disc: "thinBloodAlchemy", name: "Blood of Mandagloire", level: 2, cost: "One Rouse Check", source: "Second Inquisition", desc: "Distillate: taint a herd's blood so feeders collapse into dreamless sleep." }),
  Power({ disc: "thinBloodAlchemy", name: "Blue State", level: 2, cost: "One Rouse Check", source: "Blood Sigils", desc: "Distillate: fixate a target obsessively on an ally's failure." }),
  Power({ disc: "thinBloodAlchemy", name: "Envelop", level: 2, cost: "One Rouse Check", pool: "Wits + Alchemy", opp: "Stamina + Survival", desc: "Distillate: smother a target in a suffocating cloud." }),
  Power({ disc: "thinBloodAlchemy", name: "Friends List", level: 2, cost: "One Rouse Check", pool: "Intelligence + Alchemy", source: "Players Guide", desc: "Distillate: perceive the bonds linking Kindred and mortals together." }),
  Power({ disc: "thinBloodAlchemy", name: "Mirror of Trust", level: 2, cost: "One Rouse Check", source: "Second Inquisition", desc: "Distillate: bolster your efforts to persuade or intimidate someone into honesty." }),
  Power({ disc: "thinBloodAlchemy", name: "Red's Flaming Hot Sauce", level: 2, source: "Winter's Teeth", desc: "Distillate: hurl a supernatural firebomb whose flames cannot be fully quenched." }),
  Power({ disc: "thinBloodAlchemy", name: "Whiff-Its", level: 2, cost: "One Rouse Check", pool: "Resolve + Awareness", source: "Gehenna War", desc: "Distillate: scent and track whichever Kindred holds the greatest Blood Potency." }),
  Power({ disc: "thinBloodAlchemy", name: "Counterfeit Discipline", level: 2, cost: "The same as the power channeled", pool: "The same as the power channeled", opp: "The same as the power channeled", desc: "Distillate: mimic a chosen one-dot Discipline power as though your own." }),
  Power({ disc: "thinBloodAlchemy", name: "Bleed Out", level: 3, cost: "One Rouse Check", source: "Tattered Façade", desc: "Distillate: liquefy a victim's organs into blood feeding a whole coterie." }),
  Power({ disc: "thinBloodAlchemy", name: "Chemically-Induced Flashback", level: 3, cost: "One Rouse Check in addition to the use of Ashe", source: "Cults of the Blood Gods", desc: "Distillate: imbibe and relive a captured memory of another vampire." }),
  Power({ disc: "thinBloodAlchemy", name: "Concoct Ashe", level: 3, cost: "Free", pool: "Intelligence + Alchemy", source: "Cults of the Blood Gods", desc: "Distillate: refine Ashe from the destroyed remains of a vampire." }),
  Power({ disc: "thinBloodAlchemy", name: "Diamond Skin", level: 3, cost: "One Rouse Check", source: "Blood Sigils", desc: "Distillate: downgrade incoming physical damage from aggravated to superficial." }),
  Power({ disc: "thinBloodAlchemy", name: "Defractionate", level: 3, cost: "Free", desc: "Distillate: render stored or bagged blood drinkable to a vampire." }),
  Power({ disc: "thinBloodAlchemy", name: "Fang-Stinger", level: 3, cost: "One Rouse Check", pool: "Resolve + Alchemy", opp: "Stamina + Resolve", source: "Second Inquisition", desc: "Distillate: seed a mortal's blood to harm any vampire who drinks it." }),
  Power({ disc: "thinBloodAlchemy", name: "Fireskin", level: 3, cost: "One Rouse Check", source: "Blood Sigils", desc: "Distillate: superheat your body, adding fire to blows but worsening cold." }),
  Power({ disc: "thinBloodAlchemy", name: "Freezer Fluid", level: 3, cost: "One Rouse Check", pool: "Resolve + Alchemy", opp: "Stamina + Resolve", source: "Second Inquisition", desc: "Distillate: freeze a target vampire's body solid." }),
  Power({ disc: "thinBloodAlchemy", name: "Hospital Chains", level: 3, cost: "One Rouse Check", pool: "Distillation roll vs Stamina", source: "Blood Sigils", desc: "Distillate: block a victim from healing their wounds." }),
  Power({ disc: "thinBloodAlchemy", name: "Mandagloire", level: 3, cost: "One Rouse Check", pool: "Stamina + Alchemy", opp: "Stamina + Resolve", source: "Players Guide", desc: "Distillate: release a gas that rigidly paralyzes mortals and supernaturals." }),
  Power({ disc: "thinBloodAlchemy", name: "Martian Purity", level: 3, cost: "One Rouse Check", source: "Blood Sigils", desc: "Distillate: burn blood-borne diseases out through ignited gases at a cost." }),
  Power({ disc: "thinBloodAlchemy", name: "Mask Off", level: 3, cost: "One Rouse Check", opp: "Stamina + Resolve", source: "Blood Sigils", desc: "Distillate: burst harmless gas that strips away targets' Blush of Life." }),
  Power({ disc: "thinBloodAlchemy", name: "On-Demand Sunburn", level: 3, cost: "One Rouse Check", source: "Sabbat", desc: "Distillate: store sunlight and sear vampires with your touch." }),
  Power({ disc: "thinBloodAlchemy", name: "Profane Hieros Gamos", level: 3, cost: "One Rouse Check or One point of Aggravated Damage for mortals", pool: "Stamina + Resolve", desc: "Distillate: reshape your appearance, features, and apparent sex." }),
  Power({ disc: "thinBloodAlchemy", name: "Rumor", level: 3, cost: "One Rouse Check", pool: "Manipulation + Alchemy", opp: "Wits + Awareness", source: "Players Guide", desc: "Distillate: plant a claim that one person accepts until contradicted." }),
  Power({ disc: "thinBloodAlchemy", name: "Stay the Falling Sand", level: 3, cost: "One Rouse Check", pool: "Resolve + Alchemy", source: "Winter's Teeth", desc: "Distillate: slow time around inanimate things but not the living." }),
  Power({ disc: "thinBloodAlchemy", name: "Saraimu", level: 3, cost: "One Rouse Check", pool: "Resolve + Alchemy", source: "Tattered Façade", desc: "Distillate: birth a sentient slime blob to serve as a familiar." }),
  Power({ disc: "thinBloodAlchemy", name: "Tank", level: 3, cost: "One Rouse Check", source: "Players Guide", desc: "Distillate: harden yourself so the first hit is heavily blunted." }),
  Power({ disc: "thinBloodAlchemy", name: "TLC", level: 3, cost: "One Rouse Check", source: "Blood Sigils", desc: "Distillate: enrich animal blood so it slakes like mortal vitae." }),
  Power({ disc: "thinBloodAlchemy", name: "Troll the Pious", level: 3, cost: "One Rouse Check", source: "Blood Sigils", desc: "Distillate: afflict the devout with penalties, worse for those of True Faith." }),
  Power({ disc: "thinBloodAlchemy", name: "Airborne Momentum", level: 4, cost: "One Rouse Check", pool: "Strength + Alchemy", opp: "Strength + Athletics (if resisted)", desc: "Distillate: gain limited flight for a short time." }),
  Power({ disc: "thinBloodAlchemy", name: "Copycat", level: 4, cost: "One Rouse Check", opp: "Intelligence + Awareness", source: "Blood Sigils", desc: "Distillate: assume a rough physical likeness of another person." }),
  Power({ disc: "thinBloodAlchemy", name: "Discipline Channeling", level: 4, cost: "The same as the power channeled", source: "Cults of the Blood Gods", desc: "Distillate: infuse Ashe with Disciplines for later use." }),
  Power({ disc: "thinBloodAlchemy", name: "Half-Living Conductor", level: 4, cost: "One Rouse Check", pool: "Stamina + Alchemy", source: "Blood Sigils", desc: "Distillate: shrug off electricity and redirect it as an attack." }),
  Power({ disc: "thinBloodAlchemy", name: "Hollow Leg", level: 4, cost: "Free", pool: "Intelligence + Alchemy", opp: "Stamina + Composure", source: "Winter's Teeth", desc: "Distillate: poison a Kindred so feeding no longer slakes their Hunger." }),
  Power({ disc: "thinBloodAlchemy", name: "Juice Box", level: 4, cost: "One Rouse Check", pool: "As target Formula", opp: "As target Formula", source: "Gehenna War", desc: "Distillate: adapt a formula so any vampire can use it." }),
  Power({ disc: "thinBloodAlchemy", name: "Red State", level: 4, cost: "One Rouse Check", source: "Blood Sigils", desc: "Distillate: wipe a target's memory of someone's wrongdoings." }),
  Power({ disc: "thinBloodAlchemy", name: "Short Circuit", level: 4, cost: "One Rouse Check", source: "Players Guide", desc: "Distillate: fry electronics by touching the device or connected metal." }),
  Power({ disc: "thinBloodAlchemy", name: "Toxic Personality", level: 4, cost: "One Rouse Check", pool: "Strength/Dexterity + Alchemy", opp: "Dexterity + Alchemy", source: "Players Guide", desc: "Distillate: ooze caustic bile you can strike or spit as a weapon." }),
  Power({ disc: "thinBloodAlchemy", name: "Vitae MSG", level: 4, cost: "One Rouse Check", source: "Blood Sigils", desc: "Distillate: mark a mortal so vampires struggle to resist feeding on them." }),
  Power({ disc: "thinBloodAlchemy", name: "Awaken the Sleeper", level: 5, cost: "One Rouse Check", desc: "Distillate: rouse another vampire forcibly from daytime slumber." }),
  Power({ disc: "thinBloodAlchemy", name: "Beast Mode", level: 5, cost: "One Rouse Check", source: "Gehenna War", desc: "Distillate: wield one fifth-level Potence, Celerity, or Fortitude power." }),
  Power({ disc: "thinBloodAlchemy", name: "Da Bomb", level: 5, cost: "One Rouse Check", source: "Tattered Façade", desc: "Distillate: transform an imbibing mortal into a walking time bomb." }),
  Power({ disc: "thinBloodAlchemy", name: "Flowering Amaranth", level: 5, cost: "One Rouse Check made by each participant", pool: "Resolve + Alchemy", opp: "Willpower + Blood Potency", source: "Players Guide", desc: "Distillate: share diablerie's spoils, granting a Discipline and its telltale aura." }),
  Power({ disc: "thinBloodAlchemy", name: "Moment of Clarity", level: 5, cost: "One Rouse Check", source: "Players Guide", desc: "Distillate: channel the Beast to boost mental pools and defy frenzy." }),
  Power({ disc: "thinBloodAlchemy", name: "Saturn's Flux", level: 5, cost: "One Rouse Check", source: "Blood Sigils", desc: "Distillate: sever Blood-bonds, painlessly for mortals but costly for Kindred." }),
];

export default [...disciplines, ...powers];
