/**
 * Blood Sorcery Rituals compendium (levels 1–5).
 *
 * Every ritual listed on the Paradox VtM wiki Blood Sorcery Rituals page,
 * across the whole V5 line (Corebook, Players Guide, Blood Sigils, Chicago by
 * Night, Sabbat, Fall of London, Forbidden Religions, and more). Ritual level,
 * casting pool, and required ingredients are mechanical facts; descriptions are
 * original one-line summaries. `source` names the book (default Corebook / V5).
 */

import { Ritual } from "./_helpers.mjs";

export default [
  // Level 1
  Ritual({ level: 1, name: "Astromancy", ingredients: "The caster's blood cast as a chart", source: "Blood Sigils", desc: "Read a target's aptitudes and driving Ambition in patterns of blood." }),
  Ritual({ level: 1, name: "Beelzebeatit", source: "Sabbat", desc: "Repel wild animals from an area, though controlled creatures may still enter." }),
  Ritual({ level: 1, name: "Bind the Accusing Tongue", ingredients: "A lock of the target's hair", source: "Blood Sigils", desc: "Curse a target so they cannot speak ill of the caster." }),
  Ritual({ level: 1, name: "Blood Apocrypha", source: "Book of Nod Apocrypha", desc: "Hide a message within blood that only its intended taster receives." }),
  Ritual({ level: 1, name: "Blood Walk", ingredients: "A mouthful of the subject's blood", desc: "Read a taste of Kindred blood to learn the subject's name, sire, and lineage." }),
  Ritual({ level: 1, name: "Bloody Message", source: "Let the Streets Run Red", desc: "Reveal a hidden message to a chosen type of reader, vanishing once read." }),
  Ritual({ level: 1, name: "Blood to Water", ingredients: "A vessel of blood", source: "Gehenna War", desc: "Transmute a quantity of blood harmlessly into water." }),
  Ritual({ level: 1, name: "Clinging of the Insect", ingredients: "A living spider", desc: "Grant the caster the ability to climb walls and ceilings like an insect." }),
  Ritual({ level: 1, name: "Coax the Garden", source: "Cults of the Blood Gods", desc: "Animate nearby plants to attack anyone other than the caster." }),
  Ritual({ level: 1, name: "Craft Bloodstone", ingredients: "A small stone soaked in Vitae", desc: "Enchant a stone the caster can always sense the direction and distance of." }),
  Ritual({ level: 1, name: "Douse the Fear", source: "Cults of the Blood Gods", desc: "Temporarily suppress a vampire's instinctive terror of fire for the scene." }),
  Ritual({ level: 1, name: "Enrich the Blood", ingredients: "Herbs steeped in Vitae", source: "Forbidden Religions", desc: "Raise the nourishment a draught of mortal blood provides." }),
  Ritual({ level: 1, name: "Herd Ward (Minor)", source: "Let the Streets Run Red", desc: "Ward a single mortal to punish unauthorized feeding upon them." }),
  Ritual({ level: 1, name: "Letter Ward", source: "Let the Streets Run Red", desc: "Ward a letter to harm anyone but its intended recipient who opens it." }),
  Ritual({ level: 1, name: "Revealing the Crimson Trail", source: "Gehenna War", desc: "Expose otherwise hidden traces of spilled blood, even faded old stains." }),
  Ritual({ level: 1, name: "Seal the Brand", source: "Players Guide", desc: "Permanently fix a tattoo onto a vampire's flesh at slight cost." }),
  Ritual({ level: 1, name: "Shared Memory", source: "In Memoriam", desc: "Let participants witness another's stored memories without altering the events shown." }),
  Ritual({ level: 1, name: "Wake with Evening's Freshness", ingredients: "A feather burned to ash", desc: "Wake instantly and alert at the first sign of danger during the day's sleep." }),
  Ritual({ level: 1, name: "Ward Against Ghouls", ingredients: "Caster's Vitae drawn as a sigil", desc: "Inscribe a sigil that painfully repels ghouls who touch it." }),
  Ritual({ level: 1, name: "Blood Missive", source: "Live from the Succubus Club", desc: "Encode a message in blood that reaches whoever first tastes it." }),
  Ritual({ level: 1, name: "Sanguine Tidings", source: "Live from the Succubus Club", desc: "Make a mirror show a message when a chosen type of person approaches." }),

  // Level 2
  Ritual({ level: 2, name: "As Fog on Water", source: "Players Guide", desc: "Walk silently across water's surface for the remainder of the night." }),
  Ritual({ level: 2, name: "Calling the Aura's Remnants", source: "Chicago Folios", desc: "Question the lingering aura of the dead about what they knew in life." }),
  Ritual({ level: 2, name: "Calix Secretus", ingredients: "A hand-sized object and Vitae", source: "Players Guide", desc: "Turn an object into a hidden vessel that stores blood." }),
  Ritual({ level: 2, name: "Communicate with Kindred Sire", ingredients: "The caster's own Vitae", desc: "Open a brief one-way channel of communication toward the caster's sire." }),
  Ritual({ level: 2, name: "Craftmaster", source: "Blood Sigils", desc: "Temporarily grant skill dots and specialties in a chosen creative discipline." }),
  Ritual({ level: 2, name: "Depths of Nightmare", ingredients: "A drop of the sleeper's blood", source: "Blood Sigils", desc: "Plague a target's rest with vivid, exhausting nightmares." }),
  Ritual({ level: 2, name: "Elemental Grasp", source: "Blood Sigils", desc: "Command an element to seize a target and inflict superficial injury." }),
  Ritual({ level: 2, name: "Enhance Dyscrasia", source: "Forbidden Religions", desc: "Let several vampires share one Dyscrasia without exhausting its potency." }),
  Ritual({ level: 2, name: "Eyes of Babel", ingredients: "The tongue and an eye of a polyglot", desc: "Temporarily understand and speak languages known to the consumed victim." }),
  Ritual({ level: 2, name: "Illuminate Trail of Prey", desc: "Trace and follow the path of a specific person whose face is known." }),
  Ritual({ level: 2, name: "Le Sang de l'Amour", source: "Blood Sigils", desc: "Link two willing lovers so each can sense the other's location." }),
  Ritual({ level: 2, name: "Soporific Touch", source: "Camarilla", desc: "Spend vitae to leave a touched victim vulnerable to manipulation and mind control." }),
  Ritual({ level: 2, name: "Silentia Mortis", source: "Blood Sigils", desc: "Surround a subject with an area of magical silence." }),
  Ritual({ level: 2, name: "Shroud of Silence", source: "Forbidden Religions", desc: "Seal a room so no sound can escape it." }),
  Ritual({ level: 2, name: "Stolen Memory", source: "In Memoriam", desc: "Delve into a sire's memories, reaching older ancestors with greater difficulty." }),
  Ritual({ level: 2, name: "Tiamat Glistens", source: "Blood Sigils", desc: "Bond to a place of power to strengthen your future ritual castings." }),
  Ritual({ level: 2, name: "Truth of Blood", ingredients: "Blood of the one to be questioned", pool: "Resolve + Blood Sorcery", desc: "Compel honest answers from a subject whose blood the caster prepares." }),
  Ritual({ level: 2, name: "Unseen Underground", source: "Fall of London", desc: "Turn invisible while below ground for up to an hour." }),
  Ritual({ level: 2, name: "Viscera Garden", source: "Blood Sigils", desc: "Cultivate blood-hungry plants that devour corpses and weaken those who eat them." }),
  Ritual({ level: 2, name: "Ward against Spirits", ingredients: "Salt and the caster's Vitae", desc: "Inscribe a sigil that repels ghosts and spirits." }),
  Ritual({ level: 2, name: "Warding Circle against Ghouls", ingredients: "A ring of the caster's Vitae", desc: "Lay a circle ghouls cannot cross without suffering." }),
  Ritual({ level: 2, name: "Web of Hunger", source: "Fall of London", desc: "Shield yourself from the compelling pull of the Beckoning." }),

  // Level 3
  Ritual({ level: 3, name: "Bladed Hands", ingredients: "A blade dulled and consumed", source: "Chicago Folios", desc: "Harden the hands into edges that deal Aggravated damage." }),
  Ritual({ level: 3, name: "Bloodless Feast", source: "Forbidden Religions", desc: "Purify blood into a clear substitute that leaves drinkers prone to diablerie." }),
  Ritual({ level: 3, name: "Blood Sigil", source: "Blood Sigils", desc: "Tattoo a hidden message onto a vampire, readable only by occult senses." }),
  Ritual({ level: 3, name: "Communal Vigor", source: "Sabbat", desc: "Let a pack priest lend their Blood Potency and dominance to packmates." }),
  Ritual({ level: 3, name: "Dagon's Call", ingredients: "A drop of the target's blood, previously tasted", pool: "Resolve + Blood Sorcery", desc: "Rupture blood vessels in a victim the caster has tasted, at a distance." }),
  Ritual({ level: 3, name: "Deflection of Wooden Doom", ingredients: "A splinter of wood, snapped", desc: "Ward the caster against the first stake that would find their heart." }),
  Ritual({ level: 3, name: "Elemental Shelter", source: "Blood Sigils", desc: "Merge your body into a chosen element for concealment and protection." }),
  Ritual({ level: 3, name: "Essence of Air", desc: "Grant yourself the power of unaided flight." }),
  Ritual({ level: 3, name: "Eyes of the Past", ingredients: "A ground lens and Vitae", source: "Chicago Folios", desc: "View events that unfolded at a location in the past." }),
  Ritual({ level: 3, name: "Fire in the Blood", source: "Cults of the Blood Gods", desc: "Ignite burning agony within a victim's blood to disable them." }),
  Ritual({ level: 3, name: "Firewalker", ingredients: "A pinch of ash from a great fire", desc: "Halve the danger and terror that fire holds for the caster for a scene." }),
  Ritual({ level: 3, name: "Galvanic Ruination", ingredients: "A copper coin", source: "Sabbat", desc: "Overload and short out electrical wiring and devices nearby." }),
  Ritual({ level: 3, name: "Gentle Mind", source: "Chicago Folios", desc: "Guard another vampire's mind against frenzy through shared blood." }),
  Ritual({ level: 3, name: "Grim Chrysalis", source: "Tattered Façade", desc: "Encase yourself in a hardened blood cocoon that shields and heals you." }),
  Ritual({ level: 3, name: "Haunted House", source: "Chicago Folios", desc: "Make a haven seem convincingly haunted for years to come." }),
  Ritual({ level: 3, name: "Herd Ward (Major)", source: "Let the Streets Run Red", desc: "Ward an entire herd's dwelling against unauthorized feeding." }),
  Ritual({ level: 3, name: "Illusion of Peaceful Death", ingredients: "Grave earth and Vitae", source: "Chicago Folios", desc: "Make a corpse appear to have died a quiet, natural death." }),
  Ritual({ level: 3, name: "Illusion of Perfection", source: "Chicago Folios", desc: "Assume a forgettable, ordinary appearance to vanish into a crowd." }),
  Ritual({ level: 3, name: "Nepenthe", ingredients: "A brewed draught of Vitae", source: "Blood Sigils", desc: "Dull or erase a chosen memory in the one who drinks it." }),
  Ritual({ level: 3, name: "One with the Blade", source: "Camarilla", desc: "Claim a single weapon as yours and shield it from harm." }),
  Ritual({ level: 3, name: "Sanguine Watcher", ingredients: "The caster's Vitae given to a rat", source: "Chicago Folios", desc: "Bind a rat from Vitae as a loyal spy and messenger." }),
  Ritual({ level: 3, name: "Seeing with the Sky's Eyes", source: "Blood Sigils", desc: "Watch a target from above and learn about their location per success." }),
  Ritual({ level: 3, name: "Seeking Tiamat", source: "Blood Sigils", desc: "Sense hidden veins of power within the earth and their nearest nodes." }),
  Ritual({ level: 3, name: "Sleep of Judas", source: "Let the Streets Run Red", desc: "Drug a vampire into helpless incapacitation." }),
  Ritual({ level: 3, name: "Soul of the Hemonculus", source: "Blood Sigils", desc: "Craft a weaker miniature copy of yourself bound to obey your commands." }),
  Ritual({ level: 3, name: "Stone of the True Form", source: "Blood Sigils", desc: "Hurl a stone that strips illusions and forces altered beings back to their true shape." }),
  Ritual({ level: 3, name: "The Unseen Change", source: "Chicago Folios", desc: "Force werewolves who enter the area into their wolf form." }),
  Ritual({ level: 3, name: "Trespass", source: "Blood Sigils", desc: "Slip through a building unnoticed by flowing through gaps blood could pass." }),
  Ritual({ level: 3, name: "Viral Haruspex", source: "Blood Sigils", desc: "Draw information from everyone in an area afflicted by a chosen disease." }),
  Ritual({ level: 3, name: "Ward against Lupines", ingredients: "The blood or fur of a werewolf", desc: "Inscribe a sigil that harms werewolves who touch it." }),
  Ritual({ level: 3, name: "Warding Circle against Spirits", ingredients: "Salt and a ring of Vitae", desc: "Lay a circle that repels ghosts and spirits from an area." }),

  // Level 4
  Ritual({ level: 4, name: "Balm of Bathory", source: "Tattered Façade", desc: "Brew a mortal-blood balm that makes the user appear strikingly younger." }),
  Ritual({ level: 4, name: "Compel the Inanimate", source: "Blood Sigils", desc: "Give an object a simple order it obeys minutes later nearby." }),
  Ritual({ level: 4, name: "Defense of the Sacred Haven", ingredients: "Vitae smeared on the haven's threshold", desc: "Shield a chosen resting place from the killing light of the sun." }),
  Ritual({ level: 4, name: "Egregore Consultation", source: "Blood Sigils", desc: "Host an illness to borrow skill from everyone sharing it in the area." }),
  Ritual({ level: 4, name: "Eyes of the Nighthawk", ingredients: "A bird of prey, bound", desc: "See through the eyes of birds the caster has prepared." }),
  Ritual({ level: 4, name: "Feast of Ashes", ingredients: "The ashes of a destroyed vampire", source: "Players Guide", desc: "Draw uncanny sustenance from the ashes of the dead." }),
  Ritual({ level: 4, name: "Guided Memory", source: "Players Guide", desc: "Relive another vampire's memories under their guidance to unlock new gifts." }),
  Ritual({ level: 4, name: "Incorporeal Passage", ingredients: "A shard of mirror", desc: "Step into an intangible state, passing through solid barriers for a time." }),
  Ritual({ level: 4, name: "Innocence of the Child's Heart", source: "Chicago Folios", desc: "Block Scry the Soul from detecting diablerie or other vampiric traits." }),
  Ritual({ level: 4, name: "Innocence's Veil", source: "Gehenna War", desc: "Temporarily conceal the telltale marks of diablerie from detection." }),
  Ritual({ level: 4, name: "Invisible Chains of Binding", source: "Players Guide", desc: "Bind a victim in place, unable to move for the duration." }),
  Ritual({ level: 4, name: "Land's Sustenance", source: "Blood Sigils", desc: "Drain a place of power, corrupting it so wounds there grow worse." }),
  Ritual({ level: 4, name: "Rending the Sweet Earth", source: "Chicago Folios", desc: "Drag an earth-melded vampire up from the ground and rouse them." }),
  Ritual({ level: 4, name: "Riding the Earth's Vein", source: "Blood Sigils", desc: "Travel one-way to a random distant node along the earth's veins." }),
  Ritual({ level: 4, name: "Protean Curse", source: "Chicago Folios", desc: "Force a target other than yourself to transform into a bat." }),
  Ritual({ level: 4, name: "Ward against Cainites", ingredients: "A vial of another vampire's Vitae", desc: "Inscribe a sigil that harms Kindred who touch it." }),
  Ritual({ level: 4, name: "Warding Circle against Lupines", desc: "Erect a ward that shields the area against werewolves." }),
  Ritual({ level: 4, name: "Seek the Gathered Vitae", source: "Live from the Succubus Club", desc: "Detect gatherings of Kindred whose combined Blood Potency is substantial." }),

  // Level 5
  Ritual({ level: 5, name: "Antebrachia Ignium", source: "Cults of the Blood Gods", desc: "Wreathe your arms in fire while remaining resistant to it there." }),
  Ritual({ level: 5, name: "Atrocity's Release", source: "Gehenna War", desc: "Undo the effects of a completed diablerie, resistible by the target." }),
  Ritual({ level: 5, name: "Dominion", source: "Players Guide", desc: "Suppress Animalism, Auspex, Dominate, and Presence throughout a building." }),
  Ritual({ level: 5, name: "Eden's Bounty", ingredients: "A vessel of consecrated Vitae", source: "Cults of the Blood Gods", desc: "Call forth an abundance of restorative Vitae for the faithful." }),
  Ritual({ level: 5, name: "Elemental Attack", source: "Blood Sigils", desc: "Command your chosen element to strike a foe, chainable into a disaster." }),
  Ritual({ level: 5, name: "Escape to True Sanctuary", desc: "Open a one-way portal to a paired sanctuary circle." }),
  Ritual({ level: 5, name: "Fisher King", source: "Blood Sigils", desc: "Bind yourself to your land to draw out its hidden secrets." }),
  Ritual({ level: 5, name: "Heart of Stone", ingredients: "A stone shaped like a heart", desc: "Turn the caster's heart to stone, immune to staking but numb to emotion." }),
  Ritual({ level: 5, name: "Reawakened Vigor", source: "Gehenna War", desc: "Recover Blood Potency more quickly after prolonged torpor." }),
  Ritual({ level: 5, name: "Shaft of Belated Dissolution", ingredients: "A hawthorn stake carved with sigils", desc: "Curse a stake so that a struck vampire crumbles even if it is later removed." }),
  Ritual({ level: 5, name: "Simulacrum Gate", source: "Sabbat", desc: "Open a gate that teleports several vampires at once." }),
  Ritual({ level: 5, name: "Transferring the Soul", pool: "Intelligence + Blood Sorcery and Intelligence + Oblivion", source: "Fall of London", desc: "Seize control of a body through diablerie aided by Oblivion." }),
  Ritual({ level: 5, name: "Warding Circle against Cainites", ingredients: "A ring drawn in vampire Vitae", desc: "Lay a circle that repels and injures other Kindred." }),
];
